# Generated by Django 4.0.6 on 2022-07-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_jobpostactivatistatus_activity_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostactivatistatus',
            name='activity_job',
        ),
        migrations.RemoveField(
            model_name='jobpostactivatistatus',
            name='user',
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobpostactivatistatus'),
        ),
    ]
