# Generated by Django 4.0.6 on 2022-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_jobpostactivatistatus_activity_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostactivatistatus',
            name='status',
            field=models.CharField(max_length=30, verbose_name='지원서 상태'),
        ),
    ]
