# Generated by Django 4.0.6 on 2022-07-22 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_jobpostactivatistatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivatistatus',
            name='activity_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobpostactivity'),
        ),
        migrations.AlterField(
            model_name='jobpostactivatistatus',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='지원서 상태'),
            preserve_default=False,
        ),
    ]
