# Generated by Django 4.0.5 on 2022-06-20 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='게시 종료 시간'),
        ),
        migrations.AddField(
            model_name='article',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='게시 시작 시간'),
        ),
    ]
